export const allGeneratedCorrections = [
  {
    "sorting_grouping": "",
    "source": "Guns & Gears pg. 152",
    "name_or_header": "Long Air Repeater",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 6,
    "severity": 2,
    "issue_description": "Hands: 1",
    "reasoning": "- clear from description of this and the other air repeater\r\n- confirmed by Sayre",
    "proposed_fix": "change Hands to 2",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://paizo.com/threads/rzs43kh6?Long-air-repeater#4",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.equipment-srd.Item.Hc4qCwyO9i0Avlzt",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.usage.value",
    "module_pattern": "held-in-one-hand",
    "module_value": "held-in-two-hands",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Advanced Player's guide pg. 57",
    "name_or_header": "Alchemical Sciences",
    "subheader": "",
    "issue_type": "Inconsistency",
    "confidence": 4,
    "severity": 1,
    "issue_description": "The versatile vials do not lose their potency at the end of the day",
    "reasoning": "- the Alchemist's infused reagents (which these mimic) do not last for more than a day\r\n- RAW would allow you to stockpile vials",
    "proposed_fix": "Append: \"Just like reagents, these vials are only available until your next daily preparations.\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/pqfg5m/investigator_alchemical_sciences_methodology_raw/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.classfeatures.Item.ln2Y1a4SxlU9sizX",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Just like reagents, these vials are only available until your next daily preparations.",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Treasure Vault pg. 185",
    "name_or_header": "Expert Snowcasting",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Doesn't list Snowcasting as a prerequisite like other archetype feats of its kind",
    "reasoning": "other similar archetype feats do have such a prerequisite",
    "proposed_fix": "Add \"Prerequisite: Snowcasting\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.llDw5DqnB4LbIUCV",
    "module_action": "ADD_PREREQUISITE",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "Snowcasting",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Guns & Gears pg. 49",
    "name_or_header": "Inventor Dedication",
    "subheader": "",
    "issue_type": "Inconsistency",
    "confidence": 4,
    "severity": 2,
    "issue_description": "Doesn't allow becoming trained in a non-Crafting skill if already trained in it",
    "reasoning": "All 30 other multiclass dedications that grant trained proficiency include a sentence that lets you switch the granted skill training to a different skill to avoid redundancy waste, except this one..  In fact this is also true for all non-multiclass dedication that make you trained in a skill (except those that allow upgrading to Expert).",
    "proposed_fix": "Add 2nd sentence: \"If you were already trained in Crafting, you instead become trained in a skill of your choice.\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.JIpjpZ8VneQomkZw",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "trained in Crafting and inventor class DC.",
    "module_value": "trained in Crafting and inventor class DC; if you were already trained in Crafting, you instead become trained in a skill of your choice.",
    "module_comment": ""
  },
  {
    "sorting_grouping": "40",
    "source": "Character Guide pg. 38",
    "name_or_header": "Hard Tail",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "Add \"Your tail is in the brawling group\" ",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.0qeYP84FfQueggkx",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Your tail is in the brawling group.",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "41",
    "source": "Core Rulebook pg. 317",
    "name_or_header": "Animal Form",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "After \"These attacks are Strength based...\", add \" and are in the brawling group\".",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.wp09USMB3GIW1qbp",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "example). If your",
    "module_value": "example) and are in the brawling group. If your",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "41",
    "source": "Character Guide pg. 57",
    "name_or_header": "Lizardfolk",
    "subheader": "Claws",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "Add \"Your claws are in the brawling group\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.ancestryfeatures.Item.NfkxFWUeG6g41e8w",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Your claws are in the brawling group.",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "41",
    "source": "Character Guide pg. 58",
    "name_or_header": "Sharp Fangs",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "Add \"Your fangs are in the brawling group\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.6oJ1EdANHgYCfCeF",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Your fangs are in the brawling group.",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "41",
    "source": "Character Guide pg. 58",
    "name_or_header": "Tail Whip",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "Add \"Your tail is in the brawling group\" ",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.LLQ5SO2c44uXDFJk",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Your tail is in the brawling group.",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "41",
    "source": "Core Rulebook pg. 400",
    "name_or_header": "Untamed Shift (Wild Morph)",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "After the first bullet point, add \"These attacks are in the brawling group\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.0xR9vrt6uDFl0Umo",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "finesse traits, and",
    "module_value": "finesse traits, belong to the brawling group, and",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "71",
    "source": "Rage of Elements pg. 37",
    "name_or_header": "Molten Wire",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "After the first bullet point, add \"These attacks are in the brawling group\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.pyaPfKPAN4H7hkLM",
    "module_action": "ADD_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "attack",
    "module_comment": ""
  },
  {
    "sorting_grouping": "90",
    "source": "Rage of Elements pg. 172",
    "name_or_header": "Dive and Breach",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 3,
    "issue_description": "Has \"attack\" trait",
    "reasoning": "it's a save ability and not an attack ability",
    "proposed_fix": "Remove the attack trait",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/15jwbhj/does_dive_and_breach_incorrectly_have_the_attack/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.1xM9muPRa8hiyJtI",
    "module_action": "REMOVE_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "attack",
    "module_comment": ""
  },
  {
    "sorting_grouping": "91",
    "source": "Legacy of the Lost God pg. 77",
    "name_or_header": "Clownish Curse",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 3,
    "issue_description": "Has \"attack\" trait",
    "reasoning": "it's a save ability and not an attack ability",
    "proposed_fix": "Remove the attack trait",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/15jwbhj/does_dive_and_breach_incorrectly_have_the_attack/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.S7ylpCJyq0CYkux9",
    "module_action": "REMOVE_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "attack",
    "module_comment": ""
  },
  {
    "sorting_grouping": "91",
    "source": "Hands of the Devil pg. 73",
    "name_or_header": "Daydreamer's Curse",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 3,
    "issue_description": "Has \"attack\" trait",
    "reasoning": "it's a save ability and not an attack ability",
    "proposed_fix": "Remove the attack trait",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/15jwbhj/does_dive_and_breach_incorrectly_have_the_attack/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.dARE6VfJ3Uoq5M53",
    "module_action": "REMOVE_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "attack",
    "module_comment": ""
  },
  {
    "sorting_grouping": "91",
    "source": "Hands of the Devil pg. 73",
    "name_or_header": "Sage's Curse",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 3,
    "issue_description": "Has \"attack\" trait",
    "reasoning": "it's a save ability and not an attack ability",
    "proposed_fix": "Remove the attack trait",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/15jwbhj/does_dive_and_breach_incorrectly_have_the_attack/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.APDrC83QljsyHenB",
    "module_action": "REMOVE_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "attack",
    "module_comment": ""
  }
]