export const allGeneratedCorrections = [
  {
    "name_or_header": "Alchemical Sciences",
    "subheader": "",
    "source": "Advanced Player's guide pg. 57",
    "issue_type": "Inconsistency",
    "issue_description": "The versatile vials do not lose their potency at the end of the day",
    "severity": 1,
    "reasoning": "- the Alchemist's infused reagents (which these mimic) do not last for more than a day\n- RAW would allow you to stockpile vials",
    "confidence": 4,
    "proposed_fix": "Append: \"Just like reagents, these vials are only available until your next daily preparations.\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/pqfg5m/investigator_alchemical_sciences_methodology_raw/",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.classfeatures.Item.ln2Y1a4SxlU9sizX",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Just like reagents, these vials are only available until your next daily preparations.",
    "module_comment": "",
    "module_pid": "alchemical sciences - vials potency"
  },
  {
    "name_or_header": "Inventor Dedication",
    "subheader": "",
    "source": "Guns & Gears pg. 49",
    "issue_type": "Inconsistency",
    "issue_description": "Doesn't allow becoming trained in a non-Crafting skill if already trained in it",
    "severity": 2,
    "reasoning": "All 30 other multiclass dedications that grant trained proficiency include a sentence that lets you switch the granted skill training to a different skill to avoid redundancy waste, except this one..  In fact this is also true for all non-multiclass dedication that make you trained in a skill (except those that allow upgrading to Expert).",
    "confidence": 4,
    "proposed_fix": "Add 2nd sentence: \"If you were already trained in Crafting, you instead become trained in a skill of your choice.\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.JIpjpZ8VneQomkZw",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "trained in Crafting and inventor class DC.",
    "module_value": "trained in Crafting and inventor class DC; if you were already trained in Crafting, you instead become trained in a skill of your choice.",
    "module_comment": "",
    "module_pid": "inventor dedication - trained skill"
  },
  {
    "name_or_header": "Tehialai-Thief-Of-Ships",
    "subheader": "Tidal Gourd",
    "source": "Monsters of Myth pg. 106",
    "issue_type": "Typo or editing mistake",
    "issue_description": "Attack bonus is Extreme (off the charts)",
    "severity": 3,
    "reasoning": "likely typo",
    "confidence": 4,
    "proposed_fix": "Replace +36 with +26",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.lost-omens-monsters-of-myth-bestiary.Actor.C87bRxKDTuJXGkPG.Item.puKhUADYgUkKESYL",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.bonus.value",
    "module_pattern": "36",
    "module_value": "26",
    "module_comment": "",
    "module_pid": "tehialai-thief-of-ships - tidal gourd - attack bonus"
  },
  {
    "name_or_header": "Expert Snowcasting",
    "subheader": "",
    "source": "Treasure Vault pg. 185",
    "issue_type": "Missing rule",
    "issue_description": "Doesn't list Snowcasting as a prerequisite like other archetype feats of its kind",
    "severity": 1,
    "reasoning": "other similar archetype feats do have such a prerequisite",
    "confidence": 4,
    "proposed_fix": "Add \"Prerequisite: Snowcasting\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "200",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.llDw5DqnB4LbIUCV",
    "module_action": "ADD_PREREQUISITE",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "Snowcasting",
    "module_comment": "",
    "module_pid": "expert snowcasting - prerequisite"
  },
  {
    "name_or_header": "Master Snowcasting",
    "subheader": "",
    "source": "Treasure Vault pg. 185",
    "issue_type": "Missing rule",
    "issue_description": "Doesn't list Expert Snowcasting as a prerequisite like other archetype feats of its kind",
    "severity": 1,
    "reasoning": "other similar archetype feats do have such a prerequisite",
    "confidence": 4,
    "proposed_fix": "Add \"Prerequisite: Expert Snowcasting\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "201",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.syxJQ48bxE8NY91a",
    "module_action": "ADD_PREREQUISITE",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "Expert Snowcasting",
    "module_comment": "",
    "module_pid": "master snowcasting - prerequisite"
  },
  {
    "name_or_header": "Hard Tail",
    "subheader": "",
    "source": "Character Guide pg. 38",
    "issue_type": "Missing rule",
    "issue_description": "Does not list a weapon group for the attack",
    "severity": 1,
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization; the only reason not to include it is either because there's some \"default\" weapon group for unarmed attacks (doesn't seem so), or to make them weaker on purpose for certain characters",
    "confidence": 4,
    "proposed_fix": "Add \"Your tail is in the brawling group\" ",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/v3j9p8/tailed_goblins_hard_tail_feat_weapon_group_and/",
    "sorting_grouping": "40",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.0qeYP84FfQueggkx",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Your tail is in the brawling group.",
    "module_comment": "already in brawling",
    "module_pid": "hard tail - brawling"
  },
  {
    "name_or_header": "Animal Form",
    "subheader": "",
    "source": "Core Rulebook pg. 317",
    "issue_type": "Missing rule",
    "issue_description": "Does not list a weapon group for the attack",
    "severity": 1,
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization; the only reason not to include it is either because there's some \"default\" weapon group for unarmed attacks (doesn't seem so), or to make them weaker on purpose for certain characters",
    "confidence": 4,
    "proposed_fix": "After \"These attacks are Strength based...\", add \" and are in the brawling group\".",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "41",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.wp09USMB3GIW1qbp",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "example). If your",
    "module_value": "example) and are in the brawling group. If your",
    "module_comment": "already in brawling",
    "module_pid": "animal form - brawling"
  },
  {
    "name_or_header": "Lizardfolk",
    "subheader": "Claws",
    "source": "Character Guide pg. 57",
    "issue_type": "Missing rule",
    "issue_description": "Does not list a weapon group for the attack",
    "severity": 1,
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization; the only reason not to include it is either because there's some \"default\" weapon group for unarmed attacks (doesn't seem so), or to make them weaker on purpose for certain characters",
    "confidence": 4,
    "proposed_fix": "Add \"Your claws are in the brawling group\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "41",
    "module_uuid": "Compendium.pf2e.ancestryfeatures.Item.NfkxFWUeG6g41e8w",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Your claws are in the brawling group.",
    "module_comment": "already in brawling",
    "module_pid": "lizardfolk - claws - brawling"
  },
  {
    "name_or_header": "Untamed Shift (Wild Morph)",
    "subheader": "",
    "source": "Core Rulebook pg. 400",
    "issue_type": "Missing rule",
    "issue_description": "Does not list a weapon group for the attack",
    "severity": 1,
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization; the only reason not to include it is either because there's some \"default\" weapon group for unarmed attacks (doesn't seem so), or to make them weaker on purpose for certain characters",
    "confidence": 4,
    "proposed_fix": "After the first bullet point, add \"These attacks are in the brawling group\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "41",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.0xR9vrt6uDFl0Umo",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "finesse traits, and",
    "module_value": "finesse traits, belong to the brawling group, and",
    "module_comment": "already in brawling",
    "module_pid": "untamed shift - brawling"
  },
  {
    "name_or_header": "Grikkitog",
    "subheader": "Resistances",
    "source": "Bestiary pg. 195",
    "issue_type": "Typo or editing mistake",
    "issue_description": "missing the word \"all\" or \"physical\"",
    "severity": 1,
    "reasoning": "almost certainly should be \"physical\" because the \"(except adamantine)\" exception always appear for \"physical X\" resistances on other monsters, not for \"all X\" resistances",
    "confidence": 4,
    "proposed_fix": "Change to \"physical 10 (except adamantine)\"",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://github.com/foundryvtt/pf2e/pull/12468",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.pathfinder-bestiary.Actor.UPm2rwIevsX9Odbm",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.attributes.resistances.0.type",
    "module_pattern": "all-damage",
    "module_value": "physical",
    "module_comment": "it's currently \"resistance: all 10 (except adamantine)\"!",
    "module_pid": "grikkitog - resistance physical"
  },
  {
    "name_or_header": "Magnetic Pinions",
    "subheader": "",
    "source": "Rage of Elements pg. 30",
    "issue_type": "Ambiguity",
    "issue_description": "Doesn't clearly prevent you from making 3 attacks against 1 target",
    "severity": 3,
    "reasoning": "All other spells/abilities that allow attacking creatures 3 times have either a sentence preventing you from stacking multiple hits on the same creature (e.g. Scorching Ray (Blazing Bolt)) or have increasing MAP for each attack.\nThis one doesn't even have a sentence clarifying that you *can* attack the same creature three times.\nIt seems Too Good To Be True.",
    "confidence": 4,
    "proposed_fix": "Replace \"three attacks\" with \"attacks\"",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://paizo.com/threads/rzs43vmi?Magnetic-Pinions-Can-You-Target-1-Enemy-with\nhttps://www.reddit.com/r/Pathfinder2e/comments/16e8kpk/help_with_magnetic_pinions/ ",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.IAo6UeLgWqG7KK1x",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "All three attacks",
    "module_value": "All attacks",
    "module_comment": "",
    "module_pid": "magnetic pinions - three attacks"
  },
  {
    "name_or_header": "Storm Giant",
    "subheader": "rock",
    "source": "Bestiary 1 pg. 174",
    "issue_type": "Typo or editing mistake",
    "issue_description": "Attack bonus is Extreme (off the charts)",
    "severity": 4,
    "reasoning": "likely a typo from +27 to +37",
    "confidence": 4,
    "proposed_fix": "Change attack bonus from +37 to +27",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/18hxn87/suspect_my_dm_is_fudging_1_creatures_are_hitting/",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.pathfinder-bestiary.Actor.B0QyZEjAXUG5TsJU.Item.pVOVd7IIOsuNw3fo",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.bonus.value",
    "module_pattern": "37",
    "module_value": "27",
    "module_comment": "",
    "module_pid": "storm giant - rock - attack"
  },
  {
    "name_or_header": "Vitrifying Blast",
    "subheader": "",
    "source": "Rage of Elements pg. 97",
    "issue_type": "Typo or editing mistake",
    "issue_description": "has both a range and a cone area",
    "severity": 2,
    "reasoning": "probably mistaken range, because description mentions a cone",
    "confidence": 4,
    "proposed_fix": "Remove Range field",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.g2V4ID0pl1ZGAxZj",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.range.value",
    "module_pattern": "60 feet",
    "module_value": "",
    "module_comment": "",
    "module_pid": "vitrifying blast - range"
  },
  {
    "name_or_header": "Basilisk",
    "subheader": "Petrifying Gaze",
    "source": "Monster Core pg. 39",
    "issue_type": "Missing rule",
    "issue_description": "Does not list a duration for its slowed effect",
    "severity": 2,
    "reasoning": "the Slowed condition requires a duration (it's not Stunned).  Oddly, a similar bug was fixed for the Cockatrice in Monster Core, but was not fixed for the Basilisk",
    "confidence": 4,
    "proposed_fix": "Replace \"slowed 1.\" with \"slowed 1 for 1 minute.\"",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/dv5v26/cockatrice_and_basilisk_slowed_condition/",
    "sorting_grouping": "10",
    "module_uuid": "Compendium.pf2e.pathfinder-bestiary.Actor.rPHxXClTnoPYHYuZ.Item.tOCS9mkYR5K1LuOZ",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "{Slowed 1}.",
    "module_value": "{Slowed 1} for 1 minute.",
    "module_comment": "",
    "module_pid": "basilisk - petrifying gaze - no duration"
  },
  {
    "name_or_header": "Many spells that don't have the Aura trait (Antimagic Field, Focusing Hum, Qi Form, Incendiary Aura, Spirit Sense...)",
    "subheader": "",
    "source": "",
    "issue_type": "Missing rule",
    "issue_description": "A lot of spells with an area of \"emanation\" are missing the Aura trait, yet their description clearly implies it.\nThis is a very minor issue because almost nothing interacts with the Aura trait, and some of those emanations directly say that they follow you (which could be simplified by just using the Aura trait)",
    "severity": 1,
    "reasoning": "This issue was long debated with regards to Bless and Bane, which have only recently been errata'd to indeed have the Aura trait.  There are dozens of other spells that haven't received that errata, however.",
    "confidence": 4,
    "proposed_fix": "Add the Aura trait to all of those spells (exact list of spells is up for debate, decide one by one)",
    "fix_reliability": 4,
    "fix_commentary": "see a larger list of such spells (and some uncertain ones) here",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/wfab8i/a_lot_of_spells_and_abilities_need_to_get_the/",
    "sorting_grouping": "100",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.My7FvAoLYgGDDBzy",
    "module_action": "HARDCODED_HANDLING",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "",
    "module_comment": "module applies the following:\n/scripts/hardcodedCorrections.js#L10-L42",
    "module_pid": "aura spells - hardcoded - add aura"
  },
  {
    "name_or_header": "Bind Undead",
    "subheader": "",
    "source": "Player Core pg. 318",
    "issue_type": "Inconsistency",
    "issue_description": "Levels scale faster than rank, so higher rank versions become much less useful",
    "severity": 3,
    "reasoning": "all other spell rules that interact with levels use double the spell's level, half the target's level, etc",
    "confidence": 4,
    "proposed_fix": "Change Target entry to \"1 mindless undead creature of level 3 or lower\" and add \"Heightened (+1) Increase the maximum level of the target by 2\"",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.GUeRTriJkMlMlVrk",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.target.value",
    "module_pattern": "1 mindless undead creature with a level no greater than bind undead's spell rank",
    "module_value": "1 mindless undead creature with a level no greater than 3 (+2 per heighten)",
    "module_comment": "I was a bit lazy here",
    "module_pid": "bind undead - heighten target"
  },
  {
    "name_or_header": "Peri",
    "subheader": "speed",
    "source": "Bestiary 3 pg. 201",
    "issue_type": "Missing rule",
    "issue_description": "Missing speed",
    "severity": 2,
    "reasoning": "---",
    "confidence": 4,
    "proposed_fix": "Add \"Speed: 40 feet, fly 70 feet\"",
    "fix_reliability": 3,
    "fix_commentary": "arbitrary numbers identical to Astral Deva (similar creature)",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/10l9073/peri_speed_is_0/",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.pathfinder-bestiary-3.Actor.Lqm3acjjbLKuRUCf",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.attributes.speed",
    "module_pattern": "{\"value\":0,\"otherSpeeds\":[],\"details\":\"\"}",
    "module_value": "{\"value\":40,\"otherSpeeds\":[{\"type\":\"fly\",\"value\":70}],\"details\":\"\"}",
    "module_comment": "",
    "module_pid": "peri - missing speed"
  },
  {
    "name_or_header": "Striding Fire",
    "subheader": "Burning Rush",
    "source": "Bestiary 2 pg. 111",
    "issue_type": "Missing rule",
    "issue_description": "Missing damage",
    "severity": 3,
    "reasoning": "- it's a \"basic\" save, which implies damage\n- no effect of the save is mentioned except critical failure, which is unusual",
    "confidence": 4,
    "proposed_fix": "Replace \"must attempt a DC 24 basic Reflex save\" with \"takes 7d6 fire damage (DC 24 basic Reflex save)\"",
    "fix_reliability": 3,
    "fix_commentary": "probably 6d6 or 7d6 fire damage, comparing Ceustodaemon and Young White Dragon",
    "discussion_link": "https://paizo.com/threads/rzs431rh?Bestiary-2-is-Fantastic#14",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.pathfinder-bestiary-2.Actor.RUdP7qWg6pnKrPnh.Item.up0HVVMUk86V0DdT",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "must attempt a @Check[reflex|dc:24|basic] save",
    "module_value": "takes @Damage[7d6[fire]] damage (@Check[reflex|dc:24|basic])",
    "module_comment": "",
    "module_pid": "striding fire - missing damage"
  },
  {
    "name_or_header": "Zombie Dragon",
    "subheader": "Breath Weapon",
    "source": "Bestiary 3 pg. 303",
    "issue_type": "Missing rule",
    "issue_description": "Missing area (missing both shape and size)",
    "severity": 2,
    "reasoning": "---",
    "confidence": 4,
    "proposed_fix": "Replace \"viscera that\" with \"viscera in a 30 foot cone that\"",
    "fix_reliability": 3,
    "fix_commentary": "common area for breath weapons, description says \"wave\" so it's not a line",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/yt9jmj/zombie_dragon_breath_weapon_size/",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.pathfinder-bestiary-3.Actor.GGuT6YsRH4aXhpl3.Item.EAC12Ob2QRDH7V3R",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "viscera that",
    "module_value": "viscera in a @Template[type:cone|distance:30] that",
    "module_comment": "",
    "module_pid": "zombie dragon - missing area"
  },
  {
    "name_or_header": "Freshly Bloomed Basilisk",
    "subheader": "Petrifying Gaze",
    "source": "Kingmaker Adventure Path pg. 229",
    "issue_type": "Missing rule",
    "issue_description": "Does not list a duration for its slowed effect",
    "severity": 2,
    "reasoning": "the Slowed condition requires a duration (it's not Stunned).  Oddly, a similar bug was fixed for the Cockatrice in Monster Core, but was not fixed for the Basilisk",
    "confidence": 4,
    "proposed_fix": "Replace \"slowed 1.\" with \"slowed 1 for 1 minute.\"",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/dv5v26/cockatrice_and_basilisk_slowed_condition/",
    "sorting_grouping": "11",
    "module_uuid": "Compendium.pf2e.kingmaker-bestiary.Actor.WJ0bMCZUHJVwKYG1.Item.tOCS9mkYR5K1LuOZ",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "{Slowed 1}.",
    "module_value": "{Slowed 1} for 1 minute.",
    "module_comment": "",
    "module_pid": "freshly bloomed basilisk - petrifying gaze - no duration"
  },
  {
    "name_or_header": "Foxfire",
    "subheader": "",
    "source": "Ancestry Guide pg. 124",
    "issue_type": "Missing rule",
    "issue_description": "Uses a maximum range rather than a range increment",
    "severity": 2,
    "reasoning": "all other ranged attacks given by feats have a range increment... except for Sprite's Spark which explicitly says \"maximum range\" too, and is from the same book\ncompare Energy Beam for a nearly identical feat that uses increment rather than maximum.\nin the past, Paizo errata'd the Big boom Gun to have a 20 ft range increment rather than a 20 ft range, meaning they have made such a mistake before.",
    "confidence": 4,
    "proposed_fix": "Change \"maximum range\" to \"range increment\"",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "210",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.qCV04rZMty2TJBrX",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.rules.1.range",
    "module_pattern": "{\"max\":20}",
    "module_value": "{\"increment\":20}",
    "module_comment": "",
    "module_pid": "foxfire - range - automation"
  },
  {
    "name_or_header": "_extra_ Foxfire",
    "subheader": "",
    "source": "",
    "issue_type": "Missing rule",
    "issue_description": "(description)",
    "severity": 2,
    "reasoning": "",
    "confidence": 4,
    "proposed_fix": "",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "211",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.qCV04rZMty2TJBrX",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "maximum range",
    "module_value": "range increment",
    "module_comment": "",
    "module_pid": "foxfire - range - description"
  },
  {
    "name_or_header": "Sprite's Spark",
    "subheader": "",
    "source": "Ancestry Guide pg. 130",
    "issue_type": "Missing rule",
    "issue_description": "Uses a maximum range rather than a range increment",
    "severity": 2,
    "reasoning": "",
    "confidence": 4,
    "proposed_fix": "Change \"maximum range\" to \"range increment\"",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "212",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.0fTHqIqXCwGKiykR",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.rules.1.range",
    "module_pattern": "{\"max\":20}",
    "module_value": "{\"increment\":20}",
    "module_comment": "",
    "module_pid": "sprites spark - range - automation"
  },
  {
    "name_or_header": "_extra_ Sprite's Spark",
    "subheader": "",
    "source": "",
    "issue_type": "Missing rule",
    "issue_description": "(description)",
    "severity": 2,
    "reasoning": "",
    "confidence": 4,
    "proposed_fix": "",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "212",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.0fTHqIqXCwGKiykR",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "maximum range",
    "module_value": "range increment",
    "module_comment": "",
    "module_pid": "sprites spark - range - description"
  },
  {
    "name_or_header": "Elemental Bulwark",
    "subheader": "",
    "source": "Ancestry Guide pg. 111",
    "issue_type": "Missing rule",
    "issue_description": "Does not apply to non-spell effects with an elemental trait",
    "severity": 2,
    "reasoning": "seems like a blindspot (especially since this came out before kineticists)",
    "confidence": 3,
    "proposed_fix": "Change \"a spell\" to \"an effect\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.IUVzB39pRVyBFOEx",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "a spell that",
    "module_value": "an effect that",
    "module_comment": "",
    "module_pid": "elemental bulwark - a spell"
  },
  {
    "name_or_header": "Gibbering Mouther",
    "subheader": "Engulf",
    "source": "Bestiary 1 pg. 176",
    "issue_type": "Inconsistency",
    "issue_description": "Costs 1 action",
    "severity": 4,
    "reasoning": "- Engulf is 2 actions in its description and in every other monster\n- includes two Strides and an offensive ability, too much for 1 action",
    "confidence": 3,
    "proposed_fix": "Change cost from 1 to 2 actions",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/p7xrsq/gibbering_mouther_engulf_ability/",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.pathfinder-bestiary.Actor.dEAneTvoPuQXZoLR.Item.N5NccQ5JtdXMWjA9",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.actions.value",
    "module_pattern": "1",
    "module_value": "2",
    "module_comment": "",
    "module_pid": "gibbering mouther - engulf 2"
  },
  {
    "name_or_header": "Decaying (rune) (x2)",
    "subheader": "",
    "source": "GM Core pg. 237",
    "issue_type": "Typo or editing mistake",
    "issue_description": "Should not have the Acid Trait",
    "severity": 1,
    "reasoning": "likely editing mistake if copied from Corrosive.  the rune applies void damage and has the void trait.",
    "confidence": 3,
    "proposed_fix": "Remove the Acid Trait",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "170",
    "module_uuid": "Compendium.pf2e.equipment-srd.Item.fyiW23MFe8p06KL5",
    "module_action": "REMOVE_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "acid",
    "module_comment": "",
    "module_pid": "decaying rune - remove acid - lesser"
  },
  {
    "name_or_header": "_extra_ Decaying (rune)",
    "subheader": "",
    "source": "",
    "issue_type": "Typo or editing mistake",
    "issue_description": "(greater)",
    "severity": 1,
    "reasoning": "",
    "confidence": 3,
    "proposed_fix": "",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "171",
    "module_uuid": "Compendium.pf2e.equipment-srd.Item.HGsA5gXtaAA65n9e",
    "module_action": "REMOVE_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "acid",
    "module_comment": "",
    "module_pid": "decaying rune - remove acid - greater"
  },
  {
    "name_or_header": "Mycoweave Shield (x3)",
    "subheader": "",
    "source": "Mantle of Gold pg. 85",
    "issue_type": "Logical flaw",
    "issue_description": "The activation of the shield is a reaction",
    "severity": 3,
    "reasoning": "A character wielding the shield will almost never have a reaction ready, because the shield is only likely to be broken after having spent a reaction to Shield Block",
    "confidence": 3,
    "proposed_fix": "Change activation from reaction to free action",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/182njvz/mycoweave_shield/",
    "sorting_grouping": "180",
    "module_uuid": "Compendium.pf2e.equipment-srd.Item.AXewacUHP6rs980k",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": ">R<",
    "module_value": ">F<",
    "module_comment": "",
    "module_pid": "mycoweave shield - activation - lesser"
  },
  {
    "name_or_header": "_extra_ Mycoweave Shield",
    "subheader": "",
    "source": "",
    "issue_type": "Logical flaw",
    "issue_description": "(greater)",
    "severity": 3,
    "reasoning": "",
    "confidence": 3,
    "proposed_fix": "",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "181",
    "module_uuid": "Compendium.pf2e.equipment-srd.Item.i8UuRf5yLztt43TN",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": ">R<",
    "module_value": ">F<",
    "module_comment": "",
    "module_pid": "mycoweave shield - activation - greater"
  },
  {
    "name_or_header": "_extra_ Mycoweave Shield",
    "subheader": "",
    "source": "",
    "issue_type": "Logical flaw",
    "issue_description": "(major)",
    "severity": 3,
    "reasoning": "",
    "confidence": 3,
    "proposed_fix": "",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "181",
    "module_uuid": "Compendium.pf2e.equipment-srd.Item.Ruul32xBBYYVwFHC",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": ">R<",
    "module_value": ">F<",
    "module_comment": "",
    "module_pid": "mycoweave shield - activation - major"
  },
  {
    "name_or_header": "Dread Secret",
    "subheader": "",
    "source": "Advanced Player's guide pg. 231",
    "issue_type": "Unintended consequence",
    "issue_description": "Duration is either unecessary, or abruptly ends the \"loses its resistance until the end of your next turn\" condition and the \"frightened 3\" condition",
    "severity": 2,
    "reasoning": "- the resistance loss condition can't be longer than the spell's duration\n- most other spells/abilities that cause Frightened 3 have a duration of 3 rounds, 1 minute, or \"varies\"",
    "confidence": 3,
    "proposed_fix": "Change duration from \"until the start of your next turn\" to \"varies\"",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/osw42b/dread_secret_duration/",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.XULNb8ItUsfupxqH",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.duration.value",
    "module_pattern": "until the start of your next turn",
    "module_value": "varies",
    "module_comment": "",
    "module_pid": "dread secret - duration"
  },
  {
    "name_or_header": "Hydraulic Push",
    "subheader": "",
    "source": "Core Rulebook pg. 344",
    "issue_type": "Inconsistency",
    "issue_description": "The critical damage is technically not double the normal damage, so it doesn't scale at twice the rate the normal damage does",
    "severity": 3,
    "reasoning": "Other attack spells like Polar Ray say that the spell \"deals X damage\", then Critical Success is \"double damage\" and Success is \"full damage\";  this spell is probably an exception only because the standard wasn't clear, but maybe it's intentionally weird for balance reasons",
    "confidence": 3,
    "proposed_fix": "Rephrase to fit similar spells (critical deals double the normal damage)",
    "fix_reliability": 4,
    "fix_commentary": "FoundryVTT already does this with its automation, seems to cause no complaints",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/12bg46m/do_you_generally_double_the_damage_on_critical/\nhttps://www.reddit.com/r/Pathfinder2e/comments/ueb5zc/how_much_damage_does_hydraulic_push_deal_on_a/",
    "sorting_grouping": "110",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.jfVCuOpzC6mUrf6f",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "<p>You call forth a powerful blast of pressurized water that bludgeons the target and knocks it back. Make a ranged spell attack roll.</p>\n<hr />\n<p><strong>Critical Success</strong> The target takes 6d6 bludgeoning damage and is knocked back 10 feet.</p>\n<p><strong>Success</strong> The target takes 3d6 bludgeoning damage and is knocked back 5 feet.</p>",
    "module_value": "<p>You call forth a powerful blast of pressurized water that deals 3d6 bludgeoning damage and knocks the target back. Make a ranged spell attack roll.</p>\n<hr />\n<p><strong>Critical Success</strong> The target takes double damage and is knocked back 10 feet.</p>\n<p><strong>Success</strong> The target takes full  damage and is knocked back 5 feet.</p>",
    "module_comment": "a bit ugly",
    "module_pid": "hydraulic push - critical damage"
  },
  {
    "name_or_header": "Briny Bolt",
    "subheader": "",
    "source": "They Watched the Stars pg. 80",
    "issue_type": "Inconsistency",
    "issue_description": "The critical damage is technically not double the normal damage, so it doesn't scale at twice the rate the normal damage does",
    "severity": 3,
    "reasoning": "Other attack spells like Polar Ray say that the spell \"deals X damage\", then Critical Success is \"double damage\" and Success is \"full damage\";  this spell is probably an exception only because the standard wasn't clear, but maybe it's intentionally weird for balance reasons",
    "confidence": 3,
    "proposed_fix": "Rephrase to fit similar spells (critical deals double the normal damage)",
    "fix_reliability": 4,
    "fix_commentary": "FoundryVTT already does this with its automation, seems to cause no complaints",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/12bg46m/do_you_generally_double_the_damage_on_critical/\nhttps://www.reddit.com/r/Pathfinder2e/comments/ueb5zc/how_much_damage_does_hydraulic_push_deal_on_a/",
    "sorting_grouping": "111",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.8lZhUreL1bRk1v4Z",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "<p>You hurl a bolt of saltwater from your extended hand. Make a ranged spell attack against a target within range.</p>\n<hr />\n<p><strong>Critical Success</strong> The creature takes 4d6 bludgeoning damage and is @UUID[Compendium.pf2e.conditionitems.Item.XgEqL1kFApUbl5Z2]{Blinded} for 1 round and @UUID[Compendium.pf2e.conditionitems.Item.TkIyaNPgTZFBCCuh]{Dazzled} for 1 minute as saltwater sprays into its eyes. The creature can spend an Interact action to rub its eyes and end the blinded condition, but not the dazzled condition.</p>\n<p><strong>Success</strong> The creature takes 2d6 bludgeoning damage and is blinded for 1 round. The creature can spend an Interact action wiping the salt water from its eyes to end the blinded condition.</p>",
    "module_value": "<p>You hurl a bolt of saltwater from your extended hand, which deals 2d6 bludgeoning damage. Make a ranged spell attack against a target within range.</p>\n<hr />\n<p><strong>Critical Success</strong> The creature takes double damage and is @UUID[Compendium.pf2e.conditionitems.Item.XgEqL1kFApUbl5Z2]{Blinded} for 1 round and @UUID[Compendium.pf2e.conditionitems.Item.TkIyaNPgTZFBCCuh]{Dazzled} for 1 minute as saltwater sprays into its eyes. The creature can spend an Interact action to rub its eyes and end the blinded condition, but not the dazzled condition.</p>\n<p><strong>Success</strong> The creature takes full damage and is blinded for 1 round. The creature can spend an Interact action wiping the salt water from its eyes to end the blinded condition.</p>",
    "module_comment": "",
    "module_pid": "briny bolt - critical damage"
  },
  {
    "name_or_header": "Fluid Form Staff (x3)",
    "subheader": "",
    "source": "GM Core pg. 278",
    "issue_type": "Inconsistency",
    "issue_description": "Is missing a cantrip",
    "severity": 3,
    "reasoning": "every other staff in GM Core has a cantrip",
    "confidence": 3,
    "proposed_fix": "Add the Gouging Claw cantrip to its list of spells",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/18i7tz6/collecting_errors_for_a_potential_community_errata/kdfgfpe/",
    "sorting_grouping": "150",
    "module_uuid": "Compendium.pf2e.equipment-srd.Item.B71BgdfFApkYmAjc",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "<ul>\n<li><strong>1st",
    "module_value": "<ul>\n<li><strong>Cantrip</strong> <em>@UUID[Compendium.pf2e.spells-srd.Item.MPxbKoR54gkYkqLO]{Gouging Claw}</em></li>\n<li><strong>1st",
    "module_comment": "",
    "module_pid": "fluid form staff - cantrip - lesser"
  },
  {
    "name_or_header": "_extra_ Fluid Form Staff",
    "subheader": "",
    "source": "",
    "issue_type": "Inconsistency",
    "issue_description": "(greater)",
    "severity": 3,
    "reasoning": "",
    "confidence": 3,
    "proposed_fix": "",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "151",
    "module_uuid": "Compendium.pf2e.equipment-srd.Item.bQynfb23iexSu8zU",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "<ul>\n<li><strong>1st",
    "module_value": "<ul>\n<li><strong>Cantrip</strong> <em>@UUID[Compendium.pf2e.spells-srd.Item.MPxbKoR54gkYkqLO]{Gouging Claw}</em></li>\n<li><strong>1st",
    "module_comment": "",
    "module_pid": "fluid form staff - cantrip - greater"
  },
  {
    "name_or_header": "_extra_ Fluid Form Staff",
    "subheader": "",
    "source": "",
    "issue_type": "Inconsistency",
    "issue_description": "(major)",
    "severity": 3,
    "reasoning": "",
    "confidence": 3,
    "proposed_fix": "",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "151",
    "module_uuid": "Compendium.pf2e.equipment-srd.Item.smrNvKVL976JNEab",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "<ul>\n<li><strong>1st",
    "module_value": "<ul>\n<li><strong>Cantrip</strong> <em>@UUID[Compendium.pf2e.spells-srd.Item.MPxbKoR54gkYkqLO]{Gouging Claw}</em></li>\n<li><strong>1st",
    "module_comment": "",
    "module_pid": "fluid form staff - cantrip - major"
  },
  {
    "name_or_header": "Nugrah",
    "subheader": "Primal Prepared Spells",
    "source": "Kingmaker Adventure Path pg. 183",
    "issue_type": "Typo or editing mistake",
    "issue_description": "Spell attack bonus is Extreme (off the charts)",
    "severity": 3,
    "reasoning": "spell DC is 23 and spell attack bonus is usually 8-10 below it for monsters.  Here it's +21, which is way too high, but changing to the \"obvious\" +11 is a bit less likely here",
    "confidence": 3,
    "proposed_fix": "Replace +21 with +11",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.kingmaker-bestiary.Actor.KP7uf1E8CQgzTuQy.Item.JP9GiA6aaQlXRKAE",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.spelldc.value",
    "module_pattern": "21",
    "module_value": "11",
    "module_comment": "",
    "module_pid": "nugrah - spell dc"
  },
  {
    "name_or_header": "Reverse Engineer",
    "subheader": "",
    "source": "Guns & Gears pg. 25",
    "issue_type": "Logical flaw",
    "issue_description": "This level 2 feat cannot be taken at level 2 (usually)",
    "severity": 2,
    "reasoning": "- inventors cannot have expert crafting at level 2 (outside edge cases like Free Archetype)\n- no other level 2 class feats require expert proficiency in a skill - they're all level 4\n- the near-identical feat Reverse Engineering is a level 4 feat",
    "confidence": 3,
    "proposed_fix": "Change level to 4",
    "fix_reliability": 3,
    "fix_commentary": "or keep at level 2 and remove the requirement",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/z2xfv8/inventor_feat_reverse_engineer/",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.Na1qfHd6AFAXoN1A",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.level.value",
    "module_pattern": "2",
    "module_value": "4",
    "module_comment": "",
    "module_pid": "reverse engineer - level"
  },
  {
    "name_or_header": "Stunned",
    "subheader": "",
    "source": "Player Core 1 pg. 446",
    "issue_type": "Ambiguity",
    "issue_description": "It's unclear whether becoming stunned during your turn causes your turn to immediately end",
    "severity": 4,
    "reasoning": "\"You can't act while stunned\", if treated as rules text, implies you can't act from the moment you gain the condition until your turn begins, which seems very harsh.  It also implies you can't take reactions, which does seem sensible.",
    "confidence": 3,
    "proposed_fix": "Replace \"You can't act\" with \"You can't take reactions\"",
    "fix_reliability": 3,
    "fix_commentary": "if this is done, Violent Unleash can be changed to just directly remove 1 of your actions rather than applying this condition, to avoid having an odd delay",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/y7djxm/questioning_stunned_on_turn/",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.conditionitems.Item.dfCMdR4wnpbYNTix",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "You can't act.",
    "module_value": "You can't take reactions.",
    "module_comment": "",
    "module_pid": "stunned - cant act"
  },
  {
    "name_or_header": "Covered Reload",
    "subheader": "",
    "source": "Guns & Gears pg. 109",
    "issue_type": "Logical flaw",
    "issue_description": "\"Hide, then Interact\" is technically not useful because the Hidden condition lasts until you take any action other than a few specific ones",
    "severity": 2,
    "reasoning": "the only way this can work RAW is if reloading is considered a \"particularly unobtrusive action\".  But, Paizo writers usually call such GM-fiat advantages out when they happen, e.g. with \"particularly helpful\" persistent damage removal.",
    "confidence": 2,
    "proposed_fix": "Append: \"Reloading this way does not make you cease being hidden.\"",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://paizo.com/threads/rzs43nrw?Covered-Reload-doesnt-work-with-Hide",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.actionspf2e.Item.gBhWEy3ToxQeCLQm",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Reloading this way does make you cease being hidden.",
    "module_comment": "",
    "module_pid": "covered reload - hidden"
  },
  {
    "name_or_header": "Arcane Shroud",
    "subheader": "",
    "source": "Secrets of Magic pg. 48",
    "issue_type": "Unintended consequence",
    "issue_description": "Fire Shield is not very useful given that it requires an action to raise the shield and arcane shroud only lasts until the start of your next turn.",
    "severity": 2,
    "reasoning": "this errata is only needed due to the Remaster changing Fire Shield to act this way",
    "confidence": 2,
    "proposed_fix": "Replace Fire Shield with Resist Energy",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/17w52aa/did_arcane_shroud_get_nerfed_to_the_ground/",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.XydqgTE4J119J5JV",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "@UUID[Compendium.pf2e.spells-srd.Item.YrzBLPLd3r9m6t1p]{Fire Shield}",
    "module_value": "@UUID[Compendium.pf2e.spells-srd.Item.Fr58LDSrbndgld9n]{Resist Energy}",
    "module_comment": "",
    "module_pid": "arcane shroud - fire shield"
  },
  {
    "name_or_header": "Fresh Produce",
    "subheader": "",
    "source": "Rage of Elements pg. 34",
    "issue_type": "Inconsistency",
    "issue_description": "Scales in a strange manner, starts with 1d4+1 healing but then scales by 1d4+5",
    "severity": 2,
    "reasoning": "- 99% of damaging abilities in this game start and heighten with the same numbers (or a multiple of the same base)\n- 1d4+1 as baseline is possibly underpowered",
    "confidence": 2,
    "proposed_fix": "Replace \"1d4+1\" with \"1d4+5\"",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/155l87g/kineticist_fresh_produce_impulse_scaling/",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.IcAEMf94XoTvtzAO",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "<p>You grow a nourishing nut, vegetable, seed, or fruit. Choose a creature in your kinetic aura. The produce grows in their open hand, or at their feet if they have no open hands. The produce has light Bulk. A creature can eat it with an Interact action to regain 1d4+1 HP; this is a healing vitality effect. The creature feels full for 10 minutes, during which it has resistance 2 to void damage and can't eat another piece of produce. Produce not consumed by the start of your next turn withers away.</p>\n<p>@UUID[Compendium.pf2e.feat-effects.Item.2GWZgsvMJF9DN0DO]{Effect: Fresh Produce}</p>\n<hr />\n<p><strong>Level (+2)</strong> The healing increases by 1d4+5, and the resistance increases by 2.</p>\n<p>[[/r ((floor((max(1,@actor.level)-1)/2)+1)d4+(floor((max(1,@actor.level)-1)/2)*5+1))[vitality,healing]]]{Leveled HP}</p>",
    "module_value": "<p>You grow a nourishing nut, vegetable, seed, or fruit. Choose a creature in your kinetic aura. The produce grows in their open hand, or at their feet if they have no open hands. The produce has light Bulk. A creature can eat it with an Interact action to regain 1d4+4 HP; this is a healing vitality effect. The creature feels full for 10 minutes, during which it has resistance 2 to void damage and can't eat another piece of produce. Produce not consumed by the start of your next turn withers away.</p>\n<p>@UUID[Compendium.pf2e.feat-effects.Item.2GWZgsvMJF9DN0DO]{Effect: Fresh Produce}</p>\n<hr />\n<p><strong>Level (+2)</strong> The healing increases by 1d4+5, and the resistance increases by 2.</p>\n<p>[[/r (ceil(max(1,@actor.level)/2))d4+ceil(max(1,@actor.level)/2)*5[vitality,healing]]]{Leveled HP}</p>",
    "module_comment": "",
    "module_pid": "fresh produce - numbers"
  },
  {
    "name_or_header": "Percussive Impact",
    "subheader": "",
    "source": "Firebrands pg. 90",
    "issue_type": "Typo or editing mistake",
    "issue_description": "The spell doesn't mention the damage doubling on a critical hit",
    "severity": 3,
    "reasoning": "This could be intended (for balance reasons), but could just as well be a mistake - hard to say.  Almost every other attack spell deals double damage on a critical hit.",
    "confidence": 2,
    "proposed_fix": "Clarify that on a critical success the target takes double damage.",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "120",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.iG1USiSRXMjCDGAr",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "critical success, the",
    "module_value": "critical success, you deal double the bludgeoning damage and",
    "module_comment": "",
    "module_pid": "percussive impact - critical"
  },
  {
    "name_or_header": "Murderous Vine",
    "subheader": "",
    "source": "Secrets of Magic pg. 117",
    "issue_type": "Typo or editing mistake",
    "issue_description": "The spell doesn't mention the damage doubling on a critical hit",
    "severity": 3,
    "reasoning": "This could be intended (for balance reasons), but could just as well be a mistake - hard to say.  Almost every other attack spell deals double damage on a critical hit.",
    "confidence": 2,
    "proposed_fix": "Clarify that on a critical success the target takes double damage.",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "sorting_grouping": "121",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.kCgkreCT6g0dipMd",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "piercing damage. At",
    "module_value": "piercing damage. On a critical success, the target takes double damage. At",
    "module_comment": "",
    "module_pid": "murderous vine - critical"
  },
  {
    "name_or_header": "Elementally Infused",
    "subheader": "",
    "source": "Rage of Elements pg. 45",
    "issue_type": "Inconsistency",
    "issue_description": "the Wood cantrip is Root Reading (utility) while the other 5 cantrips are all offensive",
    "severity": 2,
    "reasoning": "could be intentional, but still a bit inconsistent",
    "confidence": 1,
    "proposed_fix": "Replace \"Root Reading\" with \"Timber\" (or with Take Root)",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://paizo.com/threads/rzs43ulk&page=2?Rage-of-Elements-Errata#66",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.backgrounds.Item.YGJzgmHNqw9C72Kb",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "@UUID[Compendium.pf2e.spells-srd.Item.BX5UIAUarWG43Fg2]{Root Reading}",
    "module_value": "@UUID[Compendium.pf2e.spells-srd.Item.9I8mp7RkjeXbkYfx]{Timber}",
    "module_comment": "",
    "module_pid": "elementally infused - wood"
  },
  {
    "name_or_header": "Voice of the Elements",
    "subheader": "",
    "source": "Rage of Elements pg. 21",
    "issue_type": "Unintended consequence",
    "issue_description": "The second bullet point is currently useless - mindless elementals do not exist (yet?)",
    "severity": 2,
    "reasoning": "- There aren't any mindless elementals in the game (yet?), but there are a lot of elementals that don't speak any language, which might have been the intention of the writer.\n- It could also be that the intention is future-proofing.  \n- Intuitively, the feat should probably allow an Earth kineticist to comunicate with Sod Hounds, but doesn't by RAW.",
    "confidence": 1,
    "proposed_fix": "Change \"mindless elementals\" to \"elementals that don't speak a language\"",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/167gq3m/kineticist_voice_of_elements/",
    "sorting_grouping": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.4TZNsGF9LNBxAWmS",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "with mindless elementals",
    "module_value": "with elementals that don't speak a language",
    "module_comment": "",
    "module_pid": "voice of the elements - mindless elementals"
  }
]