export const allGeneratedCorrections = [
  {
    "sorting_grouping": "",
    "source": "Guns & Gears pg. 152",
    "name_or_header": "Long Air Repeater",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 6,
    "severity": 2,
    "issue_description": "Hands: 1",
    "reasoning": "- clear from description of this and the other air repeater\n- confirmed by Sayre",
    "proposed_fix": "change Hands to 2",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://paizo.com/threads/rzs43kh6?Long-air-repeater#4",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.equipment-srd.Item.Hc4qCwyO9i0Avlzt",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.usage.value",
    "module_pattern": "held-in-one-hand",
    "module_value": "held-in-two-hands",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Advanced Player's guide pg. 57",
    "name_or_header": "Alchemical Sciences",
    "subheader": "",
    "issue_type": "Inconsistency",
    "confidence": 4,
    "severity": 1,
    "issue_description": "The versatile vials do not lose their potency at the end of the day",
    "reasoning": "- the Alchemist's infused reagents (which these mimic) do not last for more than a day\n- RAW would allow you to stockpile vials",
    "proposed_fix": "Append: \"Just like reagents, these vials are only available until your next daily preparations.\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/pqfg5m/investigator_alchemical_sciences_methodology_raw/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.classfeatures.Item.ln2Y1a4SxlU9sizX",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Just like reagents, these vials are only available until your next daily preparations.",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Treasure Vault pg. 185",
    "name_or_header": "Expert Snowcasting",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Doesn't list Snowcasting as a prerequisite like other archetype feats of its kind",
    "reasoning": "other similar archetype feats do have such a prerequisite",
    "proposed_fix": "Add \"Prerequisite: Snowcasting\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.llDw5DqnB4LbIUCV",
    "module_action": "ADD_PREREQUISITE",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "Snowcasting",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Guns & Gears pg. 49",
    "name_or_header": "Inventor Dedication",
    "subheader": "",
    "issue_type": "Inconsistency",
    "confidence": 4,
    "severity": 2,
    "issue_description": "Doesn't allow becoming trained in a non-Crafting skill if already trained in it",
    "reasoning": "All 30 other multiclass dedications that grant trained proficiency include a sentence that lets you switch the granted skill training to a different skill to avoid redundancy waste, except this one..  In fact this is also true for all non-multiclass dedication that make you trained in a skill (except those that allow upgrading to Expert).",
    "proposed_fix": "Add 2nd sentence: \"If you were already trained in Crafting, you instead become trained in a skill of your choice.\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.JIpjpZ8VneQomkZw",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "trained in Crafting and inventor class DC.",
    "module_value": "trained in Crafting and inventor class DC; if you were already trained in Crafting, you instead become trained in a skill of your choice.",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Rage of Elements pg. 84",
    "name_or_header": "Jaathoom Shuyookh",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 4,
    "issue_description": "AC is Extreme (off the charts)",
    "reasoning": "likely a typo from +29 to +39",
    "proposed_fix": "Change AC from +39 to +29",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://paizo.com/threads/rzs43ulk&page=2?Rage-of-Elements-Errata#57",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.rage-of-elements-bestiary.Actor.O3Rjdf00nJOHF4PE",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.attributes.ac.value",
    "module_pattern": "39",
    "module_value": "29",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Treasure Vault pg. 185",
    "name_or_header": "Master Snowcasting",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Doesn't list Expert Snowcasting as a prerequisite like other archetype feats of its kind",
    "reasoning": "other similar archetype feats do have such a prerequisite",
    "proposed_fix": "Add \"Prerequisite: Expert Snowcasting\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.syxJQ48bxE8NY91a",
    "module_action": "ADD_PREREQUISITE",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "Expert Snowcasting",
    "module_comment": ""
  },
  {
    "sorting_grouping": "40",
    "source": "Character Guide pg. 38",
    "name_or_header": "Hard Tail",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "Add \"Your tail is in the brawling group\" ",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.0qeYP84FfQueggkx",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Your tail is in the brawling group.",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "41",
    "source": "Core Rulebook pg. 317",
    "name_or_header": "Animal Form",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "After \"These attacks are Strength based...\", add \" and are in the brawling group\".",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.wp09USMB3GIW1qbp",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "example). If your",
    "module_value": "example) and are in the brawling group. If your",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "41",
    "source": "Character Guide pg. 57",
    "name_or_header": "Lizardfolk",
    "subheader": "Claws",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "Add \"Your claws are in the brawling group\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.ancestryfeatures.Item.NfkxFWUeG6g41e8w",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Your claws are in the brawling group.",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "41",
    "source": "Character Guide pg. 58",
    "name_or_header": "Sharp Fangs",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "Add \"Your fangs are in the brawling group\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.6oJ1EdANHgYCfCeF",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Your fangs are in the brawling group.",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "41",
    "source": "Character Guide pg. 58",
    "name_or_header": "Tail Whip",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "Add \"Your tail is in the brawling group\" ",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.LLQ5SO2c44uXDFJk",
    "module_action": "APPEND",
    "module_field_key": "system.description.value",
    "module_pattern": "",
    "module_value": " Your tail is in the brawling group.",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "41",
    "source": "Core Rulebook pg. 400",
    "name_or_header": "Untamed Shift (Wild Morph)",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "After the first bullet point, add \"These attacks are in the brawling group\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.0xR9vrt6uDFl0Umo",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "finesse traits, and",
    "module_value": "finesse traits, belong to the brawling group, and",
    "module_comment": "already in brawling"
  },
  {
    "sorting_grouping": "71",
    "source": "Rage of Elements pg. 37",
    "name_or_header": "Molten Wire",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 1,
    "issue_description": "Does not list a weapon group for the attack",
    "reasoning": "other unarmed attacks usually belong to a weapon group, to determine critical specialization",
    "proposed_fix": "After the first bullet point, add \"These attacks are in the brawling group\"",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.pyaPfKPAN4H7hkLM",
    "module_action": "ADD_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "attack",
    "module_comment": ""
  },
  {
    "sorting_grouping": "90",
    "source": "Rage of Elements pg. 172",
    "name_or_header": "Dive and Breach",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 3,
    "issue_description": "Has \"attack\" trait",
    "reasoning": "it's a save ability and not an attack ability",
    "proposed_fix": "Remove the attack trait",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/15jwbhj/does_dive_and_breach_incorrectly_have_the_attack/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.1xM9muPRa8hiyJtI",
    "module_action": "REMOVE_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "attack",
    "module_comment": ""
  },
  {
    "sorting_grouping": "91",
    "source": "Legacy of the Lost God pg. 77",
    "name_or_header": "Clownish Curse",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 3,
    "issue_description": "Has \"attack\" trait",
    "reasoning": "it's a save ability and not an attack ability",
    "proposed_fix": "Remove the attack trait",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/15jwbhj/does_dive_and_breach_incorrectly_have_the_attack/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.S7ylpCJyq0CYkux9",
    "module_action": "REMOVE_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "attack",
    "module_comment": ""
  },
  {
    "sorting_grouping": "91",
    "source": "Hands of the Devil pg. 73",
    "name_or_header": "Daydreamer's Curse",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 3,
    "issue_description": "Has \"attack\" trait",
    "reasoning": "it's a save ability and not an attack ability",
    "proposed_fix": "Remove the attack trait",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/15jwbhj/does_dive_and_breach_incorrectly_have_the_attack/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.dARE6VfJ3Uoq5M53",
    "module_action": "REMOVE_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "attack",
    "module_comment": ""
  },
  {
    "sorting_grouping": "91",
    "source": "Hands of the Devil pg. 73",
    "name_or_header": "Sage's Curse",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 3,
    "issue_description": "Has \"attack\" trait",
    "reasoning": "it's a save ability and not an attack ability",
    "proposed_fix": "Remove the attack trait",
    "fix_reliability": 5,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/15jwbhj/does_dive_and_breach_incorrectly_have_the_attack/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.APDrC83QljsyHenB",
    "module_action": "REMOVE_TRAIT",
    "module_field_key": "",
    "module_pattern": "",
    "module_value": "attack",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Bestiary 1 pg. 150",
    "name_or_header": "Air Mephit",
    "subheader": "Reflex save",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 3,
    "issue_description": "Save bonus is Extreme (off the charts)",
    "reasoning": "likely a typo from +9 to +19",
    "proposed_fix": "Change Reflex from +19 to +9",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/18i7tz6/collecting_errors_for_a_potential_community_errata/kdbkx1y/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.pathfinder-bestiary.Actor.KDRlxdIUADWHI6Vr",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.saves.reflex.value",
    "module_pattern": "19",
    "module_value": "9",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Rage of Elements pg. 70",
    "name_or_header": "Cleanse Air",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 1,
    "issue_description": "text contradicts itself about future contamination",
    "reasoning": "the intention, based on the rest of the text, is that it does prevent such contamination but only for the duration",
    "proposed_fix": "Remove \" but doesn't prevent future contamination\"",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/15mm4pp/rage_of_elements_quality_control/jvi3fpv/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.ElpqHitq4FqwLURV",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": " but doesn't prevent future contamination.",
    "module_value": ".",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Rage of Elements pg. 173",
    "name_or_header": "Grasp of the Deep",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 2,
    "issue_description": "failure effect says confusing and contradictory things about damage",
    "reasoning": "it's very likely an editing oopsie that should just behave like all other spells",
    "proposed_fix": "Remove \" and takes 6d6 bludgeoning damage\" (2nd mention of 6d6)",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/17tcgva/primal_spell_grasp_of_the_deep_failure_effect/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.rwWtpZpkNYvypknx",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": " and takes @Damage[6d6[bludgeoning]] damage;",
    "module_value": ";",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Bestiary pg. 195",
    "name_or_header": "Grikkitog",
    "subheader": "Resistances",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 1,
    "issue_description": "missing the word \"all\" or \"physical\"",
    "reasoning": "almost certainly should be \"physical\" because the \"(except adamantine)\" exception always appear for \"physical X\" resistances on other monsters, not for \"all X\" resistances",
    "proposed_fix": "Change to \"physical 10 (except adamantine)\"",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://github.com/foundryvtt/pf2e/pull/12468",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.pathfinder-bestiary.Actor.UPm2rwIevsX9Odbm",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.attributes.resistances.0.type",
    "module_pattern": "all-damage",
    "module_value": "physical",
    "module_comment": "it's currently \"resistance: all 10 (except adamantine)\"!"
  },
  {
    "sorting_grouping": "",
    "source": "Rage of Elements pg. 30",
    "name_or_header": "Magnetic Pinions",
    "subheader": "",
    "issue_type": "Ambiguity",
    "confidence": 4,
    "severity": 3,
    "issue_description": "Doesn't clearly prevent you from making 3 attacks against 1 target",
    "reasoning": "All other spells/abilities that allow attacking creatures 3 times have either a sentence preventing you from stacking multiple hits on the same creature (e.g. Scorching Ray (Blazing Bolt)) or have increasing MAP for each attack.\nThis one doesn't even have a sentence clarifying that you *can* attack the same creature three times.\nIt seems Too Good To Be True.",
    "proposed_fix": "Replace \"three attacks\" with \"attacks\"",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://paizo.com/threads/rzs43vmi?Magnetic-Pinions-Can-You-Target-1-Enemy-with\n\nhttps://www.reddit.com/r/Pathfinder2e/comments/16e8kpk/help_with_magnetic_pinions/ ",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.IAo6UeLgWqG7KK1x",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "All three attacks",
    "module_value": "All attacks",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Bestiary 1 pg. 174",
    "name_or_header": "Storm Giant",
    "subheader": "rock",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 4,
    "issue_description": "Attack bonus is Extreme (off the charts)",
    "reasoning": "likely a typo from +27 to +37",
    "proposed_fix": "Change attack bonus from +37 to +27",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/18hxn87/suspect_my_dm_is_fudging_1_creatures_are_hitting/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.pathfinder-bestiary.Actor.B0QyZEjAXUG5TsJU.Item.pVOVd7IIOsuNw3fo",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.bonus.value",
    "module_pattern": "37",
    "module_value": "27",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Rage of Elements pg. 97",
    "name_or_header": "Vitrifying Blast",
    "subheader": "",
    "issue_type": "Typo or editing mistake",
    "confidence": 4,
    "severity": 2,
    "issue_description": "has both a range and a cone area",
    "reasoning": "probably mistaken range, because description mentions a cone",
    "proposed_fix": "Remove Range field",
    "fix_reliability": 4,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.g2V4ID0pl1ZGAxZj",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.range.value",
    "module_pattern": "60 feet",
    "module_value": "",
    "module_comment": ""
  },
  {
    "sorting_grouping": "80",
    "source": "Rage of Elements pg. 140",
    "name_or_header": "Ferrumnestra",
    "subheader": "Devotee Benefits",
    "issue_type": "Logical flaw",
    "confidence": 4,
    "severity": 3,
    "issue_description": "The 1st cleric spell, detect metal, is actually a cantrip and not a rank 1 spell;  also it's already a divine spell",
    "reasoning": "domain spells are given at ranks 1, 3, 5 and usually aren't already on the divine list",
    "proposed_fix": "Replace \"detect metal\" with \"fold metal\"",
    "fix_reliability": 4,
    "fix_commentary": "alternatively, replace with \nConductive Weapon",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/163ndmo/detect_metal_question/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.deities.Item.RnS5P7zX0HRPsDnt",
    "module_action": "OVERWRITE",
    "module_field_key": "system.spells.1",
    "module_pattern": "",
    "module_value": "Compendium.pf2e.spells-srd.Item.yD819yTgbBFcCh5M",
    "module_comment": ""
  },
  {
    "sorting_grouping": "80",
    "source": "Rage of Elements pg. 140",
    "name_or_header": "Ferrumnestra",
    "subheader": "Devotee Benefits",
    "issue_type": "Logical flaw",
    "confidence": 4,
    "severity": 3,
    "issue_description": "The 1st cleric spell, detect metal, is actually a cantrip and not a rank 1 spell;  also it's already a divine spell",
    "reasoning": "domain spells are given at ranks 1, 3, 5 and usually aren't already on the divine list",
    "proposed_fix": "Replace \"detect metal\" with \"fold metal\"",
    "fix_reliability": 4,
    "fix_commentary": "alternatively, replace with \nConductive Weapon",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/163ndmo/detect_metal_question/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.deities.Item.RnS5P7zX0HRPsDnt",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "detect metal",
    "module_value": "fold metal",
    "module_comment": ""
  },
  {
    "sorting_grouping": "81",
    "source": "Rage of Elements pg. 141",
    "name_or_header": "Laudinmio",
    "subheader": "Devotee Benefits",
    "issue_type": "Logical flaw",
    "confidence": 4,
    "severity": 3,
    "issue_description": "The 1st cleric spell, detect metal, is actually a cantrip and not a rank 1 spell;  also it's already a divine spell",
    "reasoning": "domain spells are given at ranks 1, 3, 5 and usually aren't already on the divine list",
    "proposed_fix": "Replace \"detect metal\" with \"fold metal\"",
    "fix_reliability": 4,
    "fix_commentary": "alternatively, replace with \nConductive Weapon",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/163ndmo/detect_metal_question/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.deities.Item.xLbSMedLDFyb8sFw",
    "module_action": "OVERWRITE",
    "module_field_key": "system.spells.1",
    "module_pattern": "",
    "module_value": "Compendium.pf2e.spells-srd.Item.yD819yTgbBFcCh5M",
    "module_comment": ""
  },
  {
    "sorting_grouping": "81",
    "source": "Rage of Elements pg. 141",
    "name_or_header": "Laudinmio",
    "subheader": "Devotee Benefits",
    "issue_type": "Logical flaw",
    "confidence": 4,
    "severity": 3,
    "issue_description": "The 1st cleric spell, detect metal, is actually a cantrip and not a rank 1 spell;  also it's already a divine spell",
    "reasoning": "domain spells are given at ranks 1, 3, 5 and usually aren't already on the divine list",
    "proposed_fix": "Replace \"detect metal\" with \"fold metal\"",
    "fix_reliability": 4,
    "fix_commentary": "alternatively, replace with \nConductive Weapon",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/163ndmo/detect_metal_question/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.deities.Item.xLbSMedLDFyb8sFw",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "detect metal",
    "module_value": "fold metal",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Player Core 1 pg. 318",
    "name_or_header": "Bind Undead",
    "subheader": "",
    "issue_type": "Inconsistency",
    "confidence": 4,
    "severity": 3,
    "issue_description": "Levels scale faster than rank, so higher rank versions become much less useful",
    "reasoning": "all other spell rules that interact with levels use double the spell's level, half the target's level, etc",
    "proposed_fix": "Change Target entry to \"1 mindless undead creature of level 3 or lower\" and add \"Heightened (+1) Increase the maximum level of the target by 2\"",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.GUeRTriJkMlMlVrk",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.target.value",
    "module_pattern": "1 mindless undead creature with a level no greater than bind undead's spell level",
    "module_value": "1 mindless undead creature with a level no greater than 3 (+2 per heighten)",
    "module_comment": "I was a bit lazy here"
  },
  {
    "sorting_grouping": "",
    "source": "Ancestry Guide pg. 124",
    "name_or_header": "Foxfire",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 2,
    "issue_description": "Uses a maximum range rather than a range increment",
    "reasoning": "all other ranged attacks have a range increment",
    "proposed_fix": "Change the words \"maximum range\" to \"range increment\"",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.qCV04rZMty2TJBrX",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.rules.1.range",
    "module_pattern": "{\"max\":20}",
    "module_value": "{\"increment\":10}",
    "module_comment": ""
  },
  {
    "sorting_grouping": "",
    "source": "Rage of Elements pg. 94",
    "name_or_header": "Glass Shield",
    "subheader": "",
    "issue_type": "Inconsistency",
    "confidence": 4,
    "severity": 2,
    "issue_description": "Heightened deals 1d4 + spellcasting modifier",
    "reasoning": "since the Remaster, such spells were al reworked (except this one) to remove spellcasting modifier",
    "proposed_fix": "Change all Heightened values to use an extra d4 instead of the modifier",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "https://www.reddit.com/r/Pathfinder2e/comments/15dyqc3/glass_shield_still_dealing_modifier_damage/",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.spells-srd.Item.cgfl9Qr46bKaA59e",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.heightening",
    "module_pattern": "{\"levels\":{\"3\":{\"damage\":{\"dtpQLfwMi5qU2XEa\":{\"applyMod\":true,\"category\":null,\"formula\":\"1d4\",\"materials\":[],\"type\":\"piercing\"}}},\"5\":{\"damage\":{\"dtpQLfwMi5qU2XEa\":{\"applyMod\":true,\"category\":null,\"formula\":\"2d4\",\"materials\":[],\"type\":\"piercing\"}}},\"7\":{\"damage\":{\"dtpQLfwMi5qU2XEa\":{\"applyMod\":true,\"category\":null,\"formula\":\"3d4\",\"materials\":[],\"type\":\"piercing\"}}},\"9\":{\"damage\":{\"dtpQLfwMi5qU2XEa\":{\"applyMod\":true,\"category\":null,\"formula\":\"4d4\",\"materials\":[],\"type\":\"piercing\"}}}},\"type\":\"fixed\"}",
    "module_value": "{\"levels\":{\"3\":{\"damage\":{\"dtpQLfwMi5qU2XEa\":{\"applyMod\":false,\"category\":null,\"formula\":\"2d4\",\"materials\":[],\"type\":\"piercing\"}}},\"5\":{\"damage\":{\"dtpQLfwMi5qU2XEa\":{\"applyMod\":false,\"category\":null,\"formula\":\"3d4\",\"materials\":[],\"type\":\"piercing\"}}},\"7\":{\"damage\":{\"dtpQLfwMi5qU2XEa\":{\"applyMod\":false,\"category\":null,\"formula\":\"4d4\",\"materials\":[],\"type\":\"piercing\"}}},\"9\":{\"damage\":{\"dtpQLfwMi5qU2XEa\":{\"applyMod\":false,\"category\":null,\"formula\":\"5d4\",\"materials\":[],\"type\":\"piercing\"}}}},\"type\":\"fixed\"}",
    "module_comment": "ugly but should work"
  },
  {
    "sorting_grouping": "60",
    "source": "Rage of Elements pg. 30",
    "name_or_header": "Scrap Barricade",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 2,
    "issue_description": "Missing a range",
    "reasoning": "(most wall spells have a range of 120 feet)",
    "proposed_fix": "Add \"within 120 feet\"",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.f01ieQOcJFY7Ta7m",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "open space that",
    "module_value": "open space within 120 feet that",
    "module_comment": ""
  },
  {
    "sorting_grouping": "61",
    "source": "Rage of Elements pg. 34",
    "name_or_header": "Wooden Palisade",
    "subheader": "",
    "issue_type": "Missing rule",
    "confidence": 4,
    "severity": 2,
    "issue_description": "Missing a range",
    "reasoning": "(most wall spells have a range of 120 feet)",
    "proposed_fix": "Add \"within 120 feet\"",
    "fix_reliability": 3,
    "fix_commentary": "",
    "discussion_link": "",
    "additional_comments": "",
    "module_uuid": "Compendium.pf2e.feats-srd.Item.zwxRIi0qqmyWlaTd",
    "module_action": "FIND_AND_REPLACE",
    "module_field_key": "system.description.value",
    "module_pattern": "open space that",
    "module_value": "open space within 120 feet that",
    "module_comment": ""
  }
]